# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# JVM arguments (??? ??)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# ?? ?? ?? (??)
# org.gradle.parallel=true

# AndroidX ??? ???
android.useAndroidX=true

# ???? ????
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# ? New Architecture ?? ????
newArchEnabled=false
reactNativeCodegenBuild=false

# JS ?? ?? (Hermes ??)
hermesEnabled=true
