# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.0'

use_frameworks! :linkage => :dynamic

prepare_react_native_project!

target 'navi' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'naviTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    "../node_modules/react-native",
    :mac_catalyst_enabled => false,
  )

  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      config.build_settings['HEADER_SEARCH_PATHS'] ||= []
      config.build_settings['HEADER_SEARCH_PATHS'] << "$(SDKROOT)/usr/include"
    end
  end
end
